{
 "title": "CRIPTOS PANDAS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PORCENTAJE CAMBIO 24H",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Pandas\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_change_24h\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"BTC\" or r[\"symbol\"] == \"ETH\" or r[\"symbol\"] == \"SOL\" or r[\"symbol\"] == \"STETH\" or r[\"symbol\"] == \"USDC\" or r[\"symbol\"] == \"USDT\" or r[\"symbol\"] == \"XRP\" or r[\"symbol\"] == \"BNB\")"
    }
   ]
  },
  {
   "title": "RANK CRIPTO",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Pandas\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rank\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"ETH\" or r[\"symbol\"] == \"BTC\" or r[\"symbol\"] == \"SOL\" or r[\"symbol\"] == \"STETH\" or r[\"symbol\"] == \"USDC\" or r[\"symbol\"] == \"USDT\" or r[\"symbol\"] == \"XRP\" or r[\"symbol\"] == \"BNB\")"
    }
   ]
  },
  {
   "title": "PRECIO CRIPTOS",
   "type": "stat",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Pandas\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price_usd\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"BNB\" or r[\"symbol\"] == \"ETH\" or r[\"symbol\"] == \"BTC\" or r[\"symbol\"] == \"SOL\" or r[\"symbol\"] == \"STETH\" or r[\"symbol\"] == \"USDC\" or r[\"symbol\"] == \"USDT\" or r[\"symbol\"] == \"XRP\")"
    }
   ]
  },
  {
   "title": "PRECIO TOTAL DE LAS CRIPTOS EN BTC",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-Pandas\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price_btc\")\n  |> filter(fn: (r) => r[\"symbol\"] == \"BNB\" or r[\"symbol\"] == \"ETH\" or r[\"symbol\"] == \"SOL\" or r[\"symbol\"] == \"STETH\" or r[\"symbol\"] == \"USDC\" or r[\"symbol\"] == \"USDT\" or r[\"symbol\"] == \"XRP\")\n  |> group(columns: [])\n  |> sum()\n"
    }
   ]
  }
 ]
}