{
 "title": "CRIPTOS VARIAS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "BITCOIN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BTC PRECIO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Bitcoin\")"
    }
   ]
  },
  {
   "title": "BTC PRECIO ACTUAL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Bitcoin\")"
    }
   ]
  },
  {
   "title": "PORCENTAJES CAMBIO BTC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_change_7d\" or r[\"_field\"] == \"percent_change_24h\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Bitcoin\")"
    }
   ]
  },
  {
   "title": "PRECIO MAXIMO BITCOIN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Bitcoin\")\n  |> max()  "
    }
   ]
  },
  {
   "title": "BITCOIN RANK",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rank\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Bitcoin\")"
    }
   ]
  },
  { "title": "ETHEREUM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "ETH PRECIO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Ethereum\")"
    }
   ]
  },
  {
   "title": "ETH PRECIO ACTUAL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Ethereum\")"
    }
   ]
  },
  {
   "title": "PORCENTAJES CAMBIO ETH",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_change_7d\" or r[\"_field\"] == \"percent_change_24h\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Ethereum\")"
    }
   ]
  },
  {
   "title": "PRECIO MAXIMO ETHEREUM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Ethereum\")\n  |> max()  "
    }
   ]
  },
  {
   "title": "ETHEREUM RANK",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rank\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Ethereum\")"
    }
   ]
  },
  { "title": "BINANCE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "BNB PRECIO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Binance Coin\")"
    }
   ]
  },
  {
   "title": "BNB PRECIO ACTUAL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Binance Coin\")"
    }
   ]
  },
  {
   "title": "PORCENTAJES CAMBIO BNB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_change_7d\" or r[\"_field\"] == \"percent_change_24h\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Binance Coin\")"
    }
   ]
  },
  {
   "title": "PRECIO MAXIMO BNB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Binance Coin\")\n  |> max()  "
    }
   ]
  },
  {
   "title": "BINANCE RANK",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rank\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Binance Coin\")"
    }
   ]
  },
  { "title": "DOGE COIN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "DOGE PRECIO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Dogecoin\")"
    }
   ]
  },
  {
   "title": "DOGE PRECIO ACTUAL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Dogecoin\")"
    }
   ]
  },
  {
   "title": "PORCENTAJES CAMBIO DOGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_change_7d\" or r[\"_field\"] == \"percent_change_24h\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Dogecoin\")"
    }
   ]
  },
  {
   "title": "PRECIO MAXIMO DOGECOIN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Dogecoin\")\n  |> max()  "
    }
   ]
  },
  {
   "title": "DOGECOIN RANK",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Criptomonedas\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rank\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Dogecoin\")"
    }
   ]
  }
 ]
}