{
 "title": "RANK10",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PORCENTAJE CAMBIO 7 DIAS",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RANK10\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_change_7d\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Binance Coin\" or r[\"tag1\"] == \"Dogecoin\" or r[\"tag1\"] == \"Ethereum\" or r[\"tag1\"] == \"Solana\" or r[\"tag1\"] == \"Staked Ether\" or r[\"tag1\"] == \"TON Station\" or r[\"tag1\"] == \"Tether\" or r[\"tag1\"] == \"USD Coin\" or r[\"tag1\"] == \"XRP\")"
    }
   ]
  },
  {
   "title": "RANK10 CRIPTO",
   "type": "stat",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "$" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RANK10\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Binance Coin\" or r[\"tag1\"] == \"Bitcoin\" or r[\"tag1\"] == \"Dogecoin\" or r[\"tag1\"] == \"Ethereum\" or r[\"tag1\"] == \"Solana\" or r[\"tag1\"] == \"Staked Ether\" or r[\"tag1\"] == \"TON Station\" or r[\"tag1\"] == \"Tether\" or r[\"tag1\"] == \"USD Coin\" or r[\"tag1\"] == \"XRP\")"
    }
   ]
  },
  {
   "title": "PRECIO EN BITCOIN",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RANK10\")\n  |> filter(fn: (r) => r[\"_field\"] == \"price_btc\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Binance Coin\" or r[\"tag1\"] == \"Dogecoin\" or r[\"tag1\"] == \"Ethereum\" or r[\"tag1\"] == \"Solana\" or r[\"tag1\"] == \"Staked Ether\" or r[\"tag1\"] == \"TON Station\" or r[\"tag1\"] == \"Tether\" or r[\"tag1\"] == \"USD Coin\" or r[\"tag1\"] == \"XRP\")"
    }
   ]
  },
  {
   "title": "MEDIA PRECIOS CRIPTOS (SIN BITCOIN)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"RETO0-NodeRed\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RANK10\")\n  |> filter(fn: (r) => r[\"_field\"] == \"precio\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"Binance Coin\" or r[\"tag1\"] == \"Dogecoin\" or r[\"tag1\"] == \"Ethereum\" or r[\"tag1\"] == \"Solana\" or r[\"tag1\"] == \"Staked Ether\" or r[\"tag1\"] == \"TON Station\" or r[\"tag1\"] == \"Tether\" or r[\"tag1\"] == \"USD Coin\" or r[\"tag1\"] == \"XRP\")"
    }
   ]
  }
 ]
}